////
Copyright 2021 Shikhar Vashistha
Copyright 2021 Cem Bassoy

Distributed under the Boost Software License, Version 1.0.
(http://www.boost.org/LICENSE_1_0.txt)
////

# Boost.Ublas: The Boost Ublas Library
:toc: left
:toclevels: 2
:idprefix:
:listing-caption: Code Example
:docinfo: private-footer

== Basic Linear and Multilinear Algebra Library

[[toc]]

uBLAS is a C++ template class library that provides http://www.netlib.org/blas[BLAS] level 1, 2, 3 functionality for dense, packed and sparse matrices. 
The design and implementation unify mathematical notation via operator overloading and efficient code generation via expression templates. 
Since 2018, uBLAS also supports basic operations for multilinear algebra operations such as the outer and inner product of higher-order tensors. 
The goal of the new tensor extension is to provide basic operations that simplify the implementation of e.g. machine learning and quantum computing algorithms.


=== Functionality

uBLAS provides templated C++ classes for dense, unit and sparse vectors, dense, identity, triangular, banded, symmetric, hermitian and sparse matrices. 
Views into vectors and matrices can be constructed via ranges, slices, adaptor classes and indirect arrays. 
The library covers the usual basic linear and multilinear algebra operations on vectors, matrices and tensors: 
reductions like different norms, addition and subtraction of vectors and matrices and multiplication with a scalar, inner and outer products of vectors, matrix vector and matrix matrix products and triangular solver. 
Similar operations are also provided for the tensor type.
The glue between containers, views and expression templated operations is a mostly https://en.wikipedia.org/wiki/Standard_Template_Library[STL] conforming iterator interface.



=== Documentation

* link:overview.html[Overview]
** link:overview.html#rationale[Rationale]
** link:overview.html#functionality[Functionality]
** link:types_overview.html[Overview of Tensor, Matrix- and Vector
Types]
** link:operations_overview.html[Overview of Tensor, Matrix and Vector
Operations]
** link:#further_information[Effective uBLAS and further information]
** link:options.html[Macros and Preprocessor Options]
* link:vector.html[Vector]
** link:vector.html#vector[Vector]
** link:vector.html#unit_vector[Unit Vector]
** link:vector.html#zero_vector[Zero Vector]
** link:vector.html#scalar_vector[Scalar Vector]
* link:vector_sparse.html[Sparse Vector]
** link:vector_sparse.html#mapped_vector[Mapped Vector]
** link:vector_sparse.html#compressed_vector[Compressed Vector]
** link:vector_sparse.html#coordinate_vector[Coordinate Vector]
* link:vector_proxy.html[Vector Proxies]
** link:vector_proxy.html#vector_range[Vector Range]
** link:vector_proxy.html#vector_slice[Vector Slice]
* link:vector_expression.html[Vector Expressions]
** link:vector_expression.html#vector_expression[Vector Expression]
** link:vector_expression.html#vector_references[Vector References]
** link:vector_expression.html#vector_operations[Vector Operations]
** link:vector_expression.html#vector_reductions[Vector Reductions]
* link:matrix.html[Matrix]
** link:matrix.html#matrix[Matrix]
** link:matrix.html#identity_matrix[Identity Matrix]
** link:matrix.html#zero_matrix[Zero Matrix]
** link:matrix.html#scalar_matrix[Scalar Matrix]
* link:triangular.html[Triangular Matrix]
** link:triangular.html#triangular_matrix[Triangular Matrix]
** link:triangular.html#triangular_adaptor[Triangular Adaptor]
* link:symmetric.html[Symmetric Matrix]
** link:symmetric.html#symmetric_matrix[Symmetric Matrix]
** link:symmetric.html#symmetric_adaptor[Symmetric Adaptor]
* link:hermitian.html[Hermitian Matrix]
** link:hermitian.html#hermitian_matrix[Hermitian Matrix]
** link:hermitian.html#hermitian_adaptor[Hermitian Adaptor]
* link:banded.html[Banded Matrix]
** link:banded.html#banded_matrix[Banded Matrix]
** link:banded.html#banded_adaptor[Banded Adaptor]
* link:matrix_sparse.html[Sparse Matrix]
** link:matrix_sparse.html#mapped_matrix[Mapped Matrix]
** link:matrix_sparse.html#compressed_matrix[Compressed Matrix]
** link:matrix_sparse.html#coordinate_matrix[Coordinate Matrix]
* link:matrix_proxy.html[Matrix Proxies]
** link:matrix_proxy.html#matrix_row[Matrix Row]
** link:matrix_proxy.html#matrix_column[Matrix Column]
** link:matrix_proxy.html#vector_range[Vector Range]
** link:matrix_proxy.html#vector_slice[Vector Slice]
** link:matrix_proxy.html#matrix_range[Matrix Range]
** link:matrix_proxy.html#matrix_slice[Matrix Slice]
* link:matrix_expression.html[Matrix Expressions]
** link:matrix_expression.html#matrix_expression[Matrix Expression]
** link:matrix_expression.html#matrix_references[Matrix References]
** link:matrix_expression.html#matrix_operations[Matrix Operations]
** link:matrix_expression.html#matrix_vector_operations[Matrix Vector
Operations]
** link:matrix_expression.html#matrix_matrix_operations[Matrix Matrix
Operations]
* link:tensor.html[Tensor]
** link:tensor.html#tensor[Tensor]
* link:tensor/tensor_expression.html[Tensor Expressions]
** link:tensor/tensor_expression.html#tensor_expression[Tensor
Expression]
** link:tensor/tensor_expression.html#binary_tensor_expression[Binary
Tensor Expression]
** link:tensor/tensor_expression.html#unary_tensor_expression[Unary
Tensor Expression]
* Storage and special containers
** link:unbounded_array.html[Unbounded Array]
** link:bounded_array.html[Bounded Array]
** link:range.html#range[Range]
** link:range.html#slice[Slice]
** link:tensor/extents.html#extents[Extents]
** link:tensor/strides.html#strides[Strides]
* link:storage_sparse.html[Sparse Storage]
** link:storage_sparse.html#map_std[Default Standard Map]
** link:storage_sparse.html#map_array[Map Array]
* Operations & Functions
** link:products.html[Special Products]
** link:blas.html[BLAS]
* uBLAS Concept definitions
** link:container_concept.html[Container Concepts]
*** link:container_concept.html#vector[Vector]
*** link:container_concept.html#matrix[Matrix]
*** link:container_concept.html#tensor[Tensor]
** link:expression_concept.html[Expression Concepts]
*** link:expression_concept.html#scalar_expression[Scalar Expression]
*** link:expression_concept.html#vector_expression[Vector Expression]
*** link:expression_concept.html#matrix_expression[Matrix Expression]
** link:storage_concept.html[Storage Concept]
** link:iterator_concept.html[Iterator Concepts]
*** link:iterator_concept.html#indexed_bidirectional_iterator[Indexed
Bidirectional Iterator]
*** link:iterator_concept.html#indexed_random_access_iterator[Indexed
Random Access Iterator]
*** link:iterator_concept.html#indexed_bidirectional_cr_iterator[Indexed
Bidirectional Column/Row Iterator]
*** link:iterator_concept.html#indexed_random_access_cr_iterator[Indexed
Random Access Column/Row Iterator]

=== Release notes

Release notes can be found link:release_notes.html[here].
[further_information]

=== Known limitations

* The implementation assumes a linear memory address model.
* Tuning was focussed on dense matrices.

=== Further Information

* https://lists.boost.org/mailman/listinfo.cgi/ublas[uBLAS mailing list]
* https://github.com/boostorg/ublas/wiki[uBLAS wiki]
* https://github.com/boostorg/ublas[Code]

==== Authors and Credits

uBLAS initially was written by Joerg Walter and Mathias Koch. 
We would like thank all contributors who has supported this library.
Amongst many contributors around the world, David Abrahams, Ed Brey, Fernando Cacciola, Juan Jose Gomez Cadenas, Beman Dawes, Matt Davies, Bob Fletcher, Kresimir Fresl, Joachim Kessel, Patrick Kowalzick, Toon Knapen, Hendrik Kueck, John Maddock, Jens Maurer, Alexei Novakov, Gary Powell, Joachim Pyras, Peter Schmitteckert, Jeremy Siek, Markus Steffl, Michael Stevens, Benedikt Weber, Martin Weiser, Gunter Winkler, Marc Zimmermann, Marco Guazzone, Nasos Iliopoulus and the members of http://www.boost.org[Boost] had a great impact and contribution helping the library to grow and mature. 

Starting with the https://github.com/BoostGSoC18/tensor/wiki[GSoC 2018 project], uBlas has been extended by a flexible tensor data type and basic tensor operations supporting general tensor contractions and the Einstein notation. 
The goal of the new tensor extension is to support the implementation of algorithms for e.g. machine learning and quantum computing applications.
The initial implementation of this extension is written by Cem Bassoy. 
Contributors of the uBLAS extension are Amit Singh, Ashar Khan, Stefan Seefeld, Cem Bassoy and the members of http://www.boost.org[Boost].

This library is currently maintained by David Bellot, Cem Bassoy and Stefan Seefeld.

=== Frequently Asked Questions

Q: Should I use uBLAS for new projects? +
A: At the time of writing (09/2012) there are a lot of good matrix
libraries available, e.g., http://www.simunova.com[MTL4],
http://arma.sourceforge.net[armadillo],
http://eigen.tuxfamily.org[eigen]. uBLAS offers a stable, well tested
set of vector and matrix classes, the typical operations for linear
algebra and solvers for triangular systems of equations. uBLAS offers
dense, structured and sparse matrices - all using similar interfaces.
And finally uBLAS offers good (but not outstanding) performance. On the
other side, the last major improvement of uBLAS was in 2008 and no
significant change was committed since 2009. So one should ask himself
some questions to aid the decision: _Availability?_ uBLAS is part of
boost and thus available in many environments. _Easy to use?_ uBLAS is
easy to use for simple things, but needs decent C++ knowledge when you
leave the path. _Performance?_ There are faster alternatives. _Cutting
edge?_ uBLAS is more than 10 years old and missed all new stuff from
C++11.

Q: I'm running the uBLAS dense vector and matrix benchmarks. Why do I
see a significant performance difference between the native C and
library implementations? +
A: uBLAS distinguishes debug mode (size and type conformance checks
enabled, expression templates disabled) and release mode (size and type
conformance checks disabled, expression templates enabled). Please
check, if the preprocessor symbol `NDEBUG` of `cassert` is defined.
`NDEBUG` enables release mode, which in turn uses expression templates.
You can optionally define `BOOST_UBLAS_NDEBUG` to disable all bounds,
structure and similar checks of uBLAS.

Q: I've written some uBLAS tests, which try to incorrectly assign
different matrix types or overrun vector and matrix dimensions. Why
don't I get a compile time or runtime diagnostic? +
A: uBLAS distinguishes debug mode (size and type conformance checks
enabled, expression templates disabled) and release mode (size and type
conformance checks disabled, expression templates enabled). Please
check, if the preprocessor symbol `NDEBUG` of `cassert` is defined.
`NDEBUG` disables debug mode, which is needed to get size and type
conformance checks.

Q: I've written some uBLAS benchmarks to measure the performance of
matrix chain multiplications like `prod (A, prod (B, C))` and see a
significant performance penalty due to the use of expression templates.
How can I disable expression templates? +
A: You do not need to disable expression templates. Please try
reintroducing temporaries using either `prod (A,` `matrix_type`
`(prod (B, C)))` or `prod (A, prod<``matrix_type` `> (B, C))`.

'''''

Copyright (©) 2000-2011 Joerg Walter, Mathias Koch, Gunter Winkler,
David Bellot +
Copyright (©) 2021 Shikhar Vashistha +
Copyright (©) 2021 Cem Bassoy +
Use, modification and distribution are subject to the Boost Software
License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt ).

