# Copyright 2018 Stefan Seefeld
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOOLSET: msvc-14.2
      CXXSTD: latest
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOOLSET: msvc-14.2
      CXXSTD: 17
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0
      CXXSTD: 11

install:
  - cd %appveyor_build_folder%
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - cd ..
  - git clone -b %BOOST_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\numeric\ublas
  - python tools/boostdep/depinst/depinst.py -I benchmarks numeric/ublas
  - xcopy %APPVEYOR_BUILD_FOLDER%\opencl.jam %USERPROFILE%
  - xcopy %APPVEYOR_BUILD_FOLDER%\clblas.jam %USERPROFILE%
  - ps: |
      # Creating %USERPROFILE%/user-config.jam file
      @'
      import os regex toolset ;
      local toolset = [ regex.split [ os.environ TOOLSET ] "-" ] ;
      using $(toolset[1]) : $(toolset[2-]:J="-") :  ;
      '@ | sc "$env:USERPROFILE/user-config.jam"
  - cmd /c bootstrap
  - b2 -j3 headers

build: off

test_script:
  - if not "%CXXSTD%" == "" set CXXSTD=cxxstd=%CXXSTD%
  - set ADDRMD=address-model=64
  - b2 -j3 libs/numeric/ublas/test toolset=%TOOLSET% %CXXSTD% %ADDRMD%
