# Copyright (c) 2020 Mohammad Ashar Khan
# Distributed under Boost Software License, Version 1.0
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: Apple Clang

on: 
  push:
    paths-ignore: 
      - '**.md'
      - 'doc/**'
  pull_request:
    paths-ignore: 
      - '**.md'
      - 'doc/**'
jobs:
  build:
    name: "Darwin 11.0 -std=c++${{matrix.cxxstd}}"
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cxxstd: [11, 17, 2a]

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare BOOST_ROOT
      run: |
        cd ${GITHUB_WORKSPACE}
        cd ..
        
        git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        
        git submodule update --init --depth=1 --jobs 8 tools/build
        git submodule update --init --depth=1 --jobs 8 libs/config
        git submodule update --init --depth=1 --jobs 8 tools/boostdep
        
        mkdir -p libs/numeric/
        cp -rp ${GITHUB_WORKSPACE}/. libs/numeric/ublas
        python tools/boostdep/depinst/depinst.py -g " --depth=1" -I benchmarks numeric/ublas
        
        ./bootstrap.sh
        ./b2 -j 8 headers
        
        echo ::set-env name=BOOST_ROOT::${PWD}
        
    - name: Prepare Build
      run: |
        echo $BOOST_ROOT
        cd $BOOST_ROOT
        
        echo "using clang : : clang++ ;" >> ~/user-config.jam;
        
    - name: Test Benchmarks
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 benchmarks toolset=clang cxxstd=${{matrix.cxxstd}}
        
    - name: Test Tensor Examples
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 examples/tensor toolset=clang cxxstd=${{matrix.cxxstd}}
        
    - name: Test Tensor
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 test/tensor toolset=clang cxxstd=${{matrix.cxxstd}}
