# Copyright (c) 2020 Mohammad Ashar Khan
# Distributed under Boost Software License, Version 1.0
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: "Clang Code Format"

on: 
  push:
    paths-ignore: 
      - '**.md'
      - 'doc/**'
  pull_request:
    paths-ignore: 
      - '**.md'
      - 'doc/**'
jobs:
  format:
    name: "Clang Code Formatting Check"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
     
      - name: Install Clang Format 10
        run: |
          sudo apt-get install -y clang-format-10
     
#      - name: "Format Codes"
#        run: clang-format-10 -i examples/tensor/*.cpp test/tensor/*.cpp include/boost/numeric/ublas/tensor/*.hpp include/boost/numeric/ublas/tensor/*/*.hpp
     
#      - name: Check diff
#        run: git diff --exit-code HEAD
