# Copyright (c) 2020 Mohammad Ashar Khan
# Copyright (c) 2021 Cem Bassoy
# Distributed under Boost Software License, Version 1.0
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: "Clang Sanitizer"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'doc/**'
jobs:
  build:
    name: "${{matrix.config.name}} with ${{matrix.config.description}} sanitizer with std=${{matrix.config.cxx}} and variant=${{matrix.config.variant}}"
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.config.container}}
      volumes:
        - /node20217:/node20217:rw,rshared
        - ${{ startsWith(matrix.config.container, 'ubuntu:1') && '/node20217:/__e/node20:ro,rshared' || ' ' }}
    strategy:
      fail-fast: false
      # If any compiler fails to compile, continue CI for next compiler in matrix instead of failing early
      matrix:
        config:
          - { name: clang, description: address and leak,   cc: clang-11, cxx: clang++-11, cxxstd: 20, variant: debug,   opt: off  , b2args: address-sanitizer=on, cxxflags: -fno-omit-frame-pointer, container: 'ubuntu:20.04' }
          - { name: clang, description: undefined behavior, cc: clang-11, cxx: clang++-11, cxxstd: 20, variant: debug,   opt: off  , b2args: undefined-sanitizer=on, ldflags: -shared-libsan, container: 'ubuntu:20.04' }
          - { name: clang, description: thread,             cc: clang-11, cxx: clang++-11, cxxstd: 20, variant: debug,   opt: off  , b2args: thread-sanitizer=on, container: 'ubuntu:20.04' }
          - { name: gcc,   description: address and leak,   cc: gcc-10,   cxx: g++-10,     cxxstd: 20, variant: release, opt: speed, b2args: address-sanitizer=on, cxxflags: -fopenmp -fno-omit-frame-pointer, ldflags: -fopenmp, container: 'ubuntu:20.04' }
#          - { name: gcc,   description: undefined behavior, cc: gcc-10,   cxx: g++-10,     cxxstd: 20, variant: release, opt: speed, b2args: undefined-sanitizer=on, cxxflags: -fopenmp, ldflags: -fopenmp, container: 'ubuntu:20.04' }
#          - { name: gcc,   description: thread,             cc: gcc-10,   cxx: g++-10,     cxxstd: 20, variant: release, opt: speed, b2args: thread-sanitizer=on, cxxflags: -fopenmp, ldflags: -fopenmp, container: 'ubuntu:20.04' }

    steps:
      - name: Setup container environment
        if: matrix.config.container
        run: |
          apt-get update
          apt-get -y install sudo python3 git g++ curl xz-utils

      - name: Install nodejs20glibc2.17
        if: ${{ startsWith( matrix.config.container, 'ubuntu:1' ) }}
        run: |
          curl -LO https://archives.boost.io/misc/node/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node

      - name: Install Clang 11
        run: sudo apt-get update && sudo apt-get install -y clang-11 clang-tools-11

      - name: Install GCC 10
        run: sudo apt-get update && sudo apt-get install -y g++-10 libomp-dev

      - name: Locate UBSan runtime
        if: matrix.config.description == 'undefined behavior'
        run: |
          UBSAN_DIR="$(dirname "$(${{matrix.config.cxx}} -print-file-name=libclang_rt.ubsan_standalone-x86_64.so)")"
          echo "UBSAN_DIR=$UBSAN_DIR"
          echo "LD_LIBRARY_PATH=$UBSAN_DIR:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Git Clone Boost.uBlas
        run: |
          cd ${GITHUB_WORKSPACE}
          cd ..

          git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          echo "BOOST_ROOT=${PWD}" >> ${GITHUB_ENV}
          echo $BOOST_ROOT

          git submodule update --init --depth=1 --jobs 8 tools/build
          git submodule update --init --depth=1 --jobs 8 libs/config
          git submodule update --init --depth=1 --jobs 8 tools/boostdep

          mkdir -p libs/numeric/
          cp -rp ${GITHUB_WORKSPACE}/. libs/numeric/ublas
          python3 tools/boostdep/depinst/depinst.py -g " --depth=1" -I benchmarks numeric/ublas

      - name: Bootstrap Boost and Compile Boost
        run: |
          cd $BOOST_ROOT
          ./bootstrap.sh
          ./b2 -j8 headers
          echo "using ${{ matrix.config.name }} : : ${{ matrix.config.cxx }} ;" >> ~/user-config.jam;
          export ASAN_OPTIONS=symbolize=1
          export ASAN_OPTIONS=detect_leaks=1

      - name: Run Tensor Examples with "${{matrix.config.description}}" sanitizer
        run: |
         cd $BOOST_ROOT/libs/numeric/ublas
         ASAN_OPTIONS=detect_leaks=1
         ASAN_OPTIONS=symbolize=1
         $BOOST_ROOT/b2 -j8 examples/tensor toolset=${{matrix.config.name}} cxxstd=${{matrix.config.cxxstd}} variant=${{matrix.config.variant}} optimization=${{matrix.config.opt}} cxxflags="${{matrix.config.cxxflags}}" linkflags="${{matrix.config.ldflags}}" ${{matrix.config.b2args}}

      - name: Run Tensor Tests with "${{matrix.config.description}}" sanitizer
        run: |
         cd $BOOST_ROOT/libs/numeric/ublas
         ASAN_OPTIONS=detect_leaks=1
         ASAN_OPTIONS=symbolize=1
         $BOOST_ROOT/b2 -j8 test/tensor toolset=${{matrix.config.name}} cxxstd=${{matrix.config.cxxstd}} variant=${{matrix.config.variant}} optimization=${{matrix.config.opt}} cxxflags="${{matrix.config.cxxflags}}" linkflags="${{matrix.config.ldflags}}" ${{matrix.config.b2args}}


